name: Mirror MLflow to ECR

on:
  schedule:
    - cron: "0 6 * * *"   # Daily at 6am UTC
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::413117505590:role/github-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch latest MLflow release
        id: mlflow
        run: |
          latest=$(curl -s https://registry.hub.docker.com/v2/repositories/mlflow/mlflow/tags?page_size=1 \
            | jq -r '.results[0].name')
          echo "MLFLOW_VERSION=$latest" >> $GITHUB_ENV

      - name: Trigger CodeBuild
        run: |
          aws codebuild start-build \
            --project-name mlflow-mirror \
            --environment-variables-override name=MLFLOW_VERSION,value=${{ env.MLFLOW_VERSION }} \
            --region $AWS_REGION

      - name: Slack notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: C01234567
          slack-message: |
            📦 MLflow mirror started
            *Version:* ${{ env.MLFLOW_VERSION }}
            *Triggered CodeBuild project:* mlflow-mirror
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Teams notification
        run: |
          payload=$(jq -n \
            --arg text "📦 MLflow mirror started for version ${{ env.MLFLOW_VERSION }} (CodeBuild: mlflow-mirror)" \
            '{text: $text}')
          curl -H "Content-Type: application/json" -d "$payload" ${{ secrets.TEAMS_WEBHOOK_URL }}
